# Generated by Django 3.1.4 on 2020-12-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vocabulary',
            new_name='Word',
        ),
    ]
