# Generated by Django 3.1.4 on 2020-12-06 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_word_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='adding_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 17, 26, 41, 675442, tzinfo=utc), verbose_name='date of adding'),
        ),
    ]
