# Generated by Django 3.1.4 on 2020-12-06 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_word_adding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='adding_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of adding'),
        ),
    ]
