# Generated by Django 3.1.4 on 2020-12-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_auto_20201206_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='test',
            field=models.CharField(default='', max_length=100, verbose_name='test'),
        ),
    ]
