# Generated by Django 3.1.4 on 2020-12-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_word_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='test',
        ),
    ]
